version: '2'
services:
  sync:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - psql
    command: sh ./startup.sh

  redis:
    image: "redis:alpine"
  psql:
    image: "postgres:9.5"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
    command: postgres -c log_min_duration_statement=1 -c log_connections=1 -c log_disconnections=1
