version: '2'
services:
  gevent:
    build: .
    ports:
      - "8001:8000"
    depends_on:
      - gpsql
    command: sh ./startup.sh
    environment:
      - MAX_CONNS=10

  redis:
    image: "redis:alpine"

  gpsql:
    image: "postgres:9.5"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
    command: postgres -c log_min_duration_statement=1 -c log_connections=1 -c log_disconnections=1
